# Generated by Django 3.2.16 on 2023-02-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeslist',
            name='location',
            field=models.CharField(choices=[('North', 'North'), ('Center', 'Center'), ('South', 'South')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placeslist',
            name='region',
            field=models.CharField(choices=[('Coast', 'Coast'), ('The Andes', 'The Andes'), ('Jungle', 'Jungle')], max_length=15),
        ),
        migrations.AlterField(
            model_name='placeslist',
            name='type_location',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Nature', 'Nature'), ('Arqueologic', 'Arqueologic'), ('Cultural', 'Cultural')], max_length=20),
        ),
    ]
