# Generated by Django 3.2.16 on 2023-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0004_auto_20230201_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeslist',
            name='place_image_src',
            field=models.ImageField(default='placeholder', upload_to='images/'),
        ),
    ]
