# Generated by Django 3.2.16 on 2023-02-01 14:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0005_alter_placeslist_place_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeslist',
            name='place_image_src',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
