# Generated by Django 3.2.16 on 2023-02-01 16:34

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peru_exp_app', '0006_alter_placeslist_place_image_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('region', models.CharField(choices=[('Coast', 'Coast'), ('The Andes', 'The Andes'), ('Jungle', 'Jungle')], max_length=15)),
                ('cardinal_location', models.CharField(choices=[('North', 'North'), ('Center', 'Center'), ('South', 'South')], max_length=20)),
                ('altitude', models.IntegerField()),
                ('type_location', models.CharField(choices=[('Beach', 'Beach'), ('Nature', 'Nature'), ('Arqueologic', 'Arqueologic'), ('Cultural', 'Cultural')], max_length=20)),
                ('info', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='peru_exp_app.place'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(to='peru_exp_app.Place'),
        ),
        migrations.DeleteModel(
            name='PlacesList',
        ),
    ]
