# Generated by Django 3.2.16 on 2023-02-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0007_auto_20230201_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank='True', related_name='interest', to='peru_exp_app.Place'),
        ),
    ]
