# Generated by Django 3.2.16 on 2023-02-09 10:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0009_auto_20230208_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
