# Generated by Django 3.2.16 on 2023-02-10 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peru_exp_app', '0010_auto_20230209_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='place',
            name='interests',
            field=models.ManyToManyField(blank='True', related_name='interest', to=settings.AUTH_USER_MODEL),
        ),
    ]
