# Generated by Django 3.2.16 on 2023-02-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0011_auto_20230210_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
