# Generated by Django 3.2.16 on 2023-02-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peru_exp_app', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=300),
        ),
    ]
